
services:
  vote:
    build:
      context: ./vote
      target: dev
    image: 791045538644.dkr.ecr.us-east-1.amazonaws.com/vote:01
#Menyatakan env untuk container dari service vote
    environment:
      - REDIS_HOST=redis
#menunggu redis healthy terlebih dahulu
    depends_on:
      redis:
        condition: service_healthy
#Menyatakan bagaimana caranya mengecek keadaan service ketika di dalam container
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
#volume (opsional)
    volumes:
     - ./vote:/usr/local/app
#port untuk mengakses container
    ports:
      - "8080:80"
#network untuk container
    networks:
      - front-tier
      - back-tier


#membuat service bernama vote
  result:
#Membuat image dari folder result
    build: ./result
    image: 791045538644.dkr.ecr.us-east-1.amazonaws.com/result:01
#Command ketika pertama kali container dijalankan
    entrypoint: nodemon --inspect=0.0.0.0 server.js
#Menyatakan env 
    environment:
      - DB_USER=admin
      - DB_PASS=smkn1nglegok
      - DB_HOST=vote_db
      - DB_NAME=voting_db
      - DB_PORT=5432
      - NODE_ENV=development
#Menunggu service db healthy
    depends_on:
      db:
        condition: service_healthy
#Menyatakan volume (opsional)
    volumes:
      - ./result:/usr/local/app
#Port aplikasi berjalan
    ports:
      - "8081:80"
      - "127.0.0.1:9229:9229"
#Networks untuk service result
    networks:
      - front-tier
      - back-tier


#Service worker
  worker:
#Membuat image dari folder worker
    build:
      context: ./worker
    image: 791045538644.dkr.ecr.us-east-1.amazonaws.com/worker:01
#Menyatakan env
    environment:
      - REDIS_HOST=redis
      - DB_HOST=vote_db
      - DB_USER=admin
      - DB_PASS=smkn1nglegok
#Menunggu redis dan db healthy
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
#Menyatakan network
    networks:
      - back-tier


#Membuat service redis
  redis:
#Mengambil image redis dari docker hub
    image: redis:alpine
#Menyatakan volume untuk redis
    volumes:
      - "./healthchecks:/healthchecks"
#Cara container memastikan bahwa redis berjalan dengan baik
    healthcheck:
      test: /healthchecks/redis.sh
      interval: "5s"
#Mengatur networks untuk redis
    networks:
      - back-tier


#Membuat service db
  db:
#Mengambil image dari docker hub
    image: postgres:15-alpine
#Menyatakan env
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "smkn1nglegok"
      POSTGRES_DB: voting_data
#Mengatur volume untuk database
    volumes:
      - "db-data:/var/lib/postgresql/data"
      - "./healthchecks:/healthchecks"
#Cara memastikan db berjalan dengan baik
    healthcheck:
      test: /healthchecks/postgres.sh
      interval: "5s"
#menyatakan network
    networks:
      - back-tier


#membuat volume
volumes:
  db-data:


#membuat network
networks:
  front-tier:
  back-tier: